services:
  - type: web
    name: polycode-pro
    env: python 3
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PORT
        value: 10000
